language: "node_js"
node_js:
  - "12"

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i 

before_install:
  - npm install -g node-gyp
  - rm -rf ~/.node-gyp/

notifications:
  email: false

sudo: false
